### ISSUE TITLE
Missing Texts on Devices Tab

### ISSUE THREAD

**Issue by skemp353** [sapmentors/SITregOrganizer#16]
I've noticed that there are some missing texts on the devices tab.

![image](https://cloud.githubusercontent.com/assets/6735410/19434915/d7f3f446-94b3-11e6-89a0-c2ba8476270f.png)

I've cloned the project and fixed them. Also took the liberty of using a more recognisable icon for the Devices tab.

![image](https://cloud.githubusercontent.com/assets/6735410/19434960/123a2ee0-94b4-11e6-9134-29cb54511f5d.png)

I've never created a pull request, but there's a first time for everything I guess if you are happy with the changes, I will give it a go, not sure what the etiquette is on this repository :-)

**Comment by gregorwolf** [comment]
Please go ahead and send the pull request.

**Comment by skemp353** [comment]
This was fixed with pull request https://github.com/sapmentors/SITregOrganizer/pull/17
