### ISSUE TITLE
Unable to drill down into participant details

### ISSUE THREAD

**Issue by skemp353** [sapmentors/SITregOrganizer#18]
I am not sure if this is a feature that is supposed to work or not, but in the participant list tab it looks like you should be able to drill down to see more details about the participant registration. You can see there is a little right arrow/chevron at the end of each line item in the list, suggesting to the user that there is more information available. 

![image](https://cloud.githubusercontent.com/assets/6735410/19472252/357b96e6-9572-11e6-9d85-7223421271c8.png)

However when you click on this nothing happens (still to be implemented?)

**Comment by gregorwolf** [comment]
I think for the moment we can get rid of the arrow. As the organizer has no authorization to change anything on the registration yet. Please feel free to correct that. 

But we already had the case that participants entered incorrect mail addresses. Also users that loose access to their S-User ID must be handled. 

I've created the issues 

- [Organizer should be able to correct participant E-Mail address #27](https://github.com/sapmentors/SITreg/issues/27)
- [Organizer should be able to created by of participant #28](https://github.com/sapmentors/SITreg/issues/28)

in the backend project to keep track of them.

**Comment by skemp353** [comment]
Ok, I will remove the arrow for now

**Comment by gregorwolf** [comment]
Now in production.
