### ISSUE TITLE
Expose Events list without authorisation

### ISSUE THREAD

**Issue by jpenninkhof** [sapmentors/SITregOrganizer#4]
It would be great if the application would expose and events list without having to login. This would allow external systems to consume the list and make it available elsewhere as well to increase the reach of the SIT event. 

I'm specifically thinking of getting the events list in the Lemonaid app.

**Comment by gregorwolf** [comment]
Hi Jan,

exactly that is already implemented. Please check the https://sitregparticipantlist-a5a504e08.dispatcher.hana.ondemand.com/ app and the service exposed at https://sapmentorsa5a504e08.hana.ondemand.com/com/sap/sapmentors/sitreg/odatapublic/service.xsodata. Please close this issue when that solves your request.

Best regards
Gregor

**Comment by jpenninkhof** [comment]
Yes, awesome. Thanks Gregor!
